[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[Adapt]]
git-tree-sha1 = "182b4f3518a049cd3b67e25102c99b530afeda82"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[Blosc]]
deps = ["BinaryProvider", "CMakeWrapper", "Compat"]
git-tree-sha1 = "e6ad305e3149d667566e0c7ec0e808dcf74b9e61"
uuid = "a74b3585-a348-5f62-a45c-50e91977d574"
version = "0.5.0"

[[BufferedStreams]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "0564a7fd529abf18afb644d7d73c30771988b5be"
uuid = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
version = "0.4.1"

[[CMakeWrapper]]
deps = ["BinDeps", "Libdl", "Parameters", "Test"]
git-tree-sha1 = "ea8aeb3a42f1a0f8aa05b7c091fae26a9ec64c96"
uuid = "d5fb7624-851a-54ee-a528-d3f3bac0b4a0"
version = "0.2.0"

[[CUDAapi]]
deps = ["Compat", "Libdl", "Logging", "MicroLogging"]
git-tree-sha1 = "5dd53aaf026b163b0f3fa742b7faa41dfc92f020"
uuid = "3895d2a7-ec45-59b8-82bb-cfc6a382f9b3"
version = "0.4.3"

[[CUDAdrv]]
deps = ["CUDAapi", "InteractiveUtils", "Libdl", "Pkg", "Printf", "Test"]
git-tree-sha1 = "b45d1db73770539235cef5d1a33aeab0e9d4c23b"
uuid = "c5f51814-7f29-56b8-a69c-e4d8f6be1fde"
version = "0.8.4"

[[CUDAnative]]
deps = ["CUDAapi", "CUDAdrv", "InteractiveUtils", "LLVM", "Libdl", "Logging", "Pkg", "Test"]
git-tree-sha1 = "c4dd23031d28a98844c734f98e4702b7d3fcd159"
uuid = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
version = "0.8.5"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "903ab7490d404e313fc9bf53942e28b1ba9307e8"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.11"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "456524c5dc9af774533e4133f9989296053c5bdd"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.2"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "cec56a50029f40f4c13e4f25bf84964fde31905a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.0"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "c478aec93ea90bb99c307a92df17a76131bf275f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.0"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "b76a441539d66a18ba34df28d34dc5b9202164a3"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.0.0"

[[CuArrays]]
deps = ["AbstractFFTs", "Adapt", "CUDAapi", "CUDAdrv", "CUDAnative", "ForwardDiff", "GPUArrays", "MacroTools", "NNlib"]
git-tree-sha1 = "c5a784ea21087312a20f9b7ab581bff6e39e7f59"
uuid = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
version = "0.6.2"

[[DataDeps]]
deps = ["DelimitedFiles", "HTTP", "Reexport", "SHA", "Test"]
git-tree-sha1 = "687644d60b0d6bc95b5a9087f2bdb68b79d2c069"
uuid = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
version = "0.5.1"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Dates", "InteractiveUtils", "LinearAlgebra", "Missings", "Printf", "Random", "Reexport", "SortingAlgorithms", "Statistics", "StatsBase", "Test", "TranscodingStreams", "Unicode", "WeakRefStrings"]
git-tree-sha1 = "1cc9493d9b659db1fa6d584afc3f73d74341e567"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.12.0"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "db8acf46717b13d6c48deb7a12007c7f85a70cf7"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.3"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "6b7b910f2b64784420fbb346b27ac39f71030f29"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.6"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Espresso]]
deps = ["LinearAlgebra", "Statistics", "Test"]
git-tree-sha1 = "df8ae51d86c72f3df5eb9a2284790dfd2c6b8820"
repo-rev = "master"
repo-url = "https://github.com/dfdx/Espresso.jl.git"
uuid = "6912e4f1-e036-58b0-9138-08d1e6358ea9"
version = "0.5.0"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Reexport", "Test"]
git-tree-sha1 = "60346335ad3aa60bfbdc358c6d1468bffbcff071"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.3"

[[FastClosures]]
deps = ["Compat"]
git-tree-sha1 = "ab31392bbdd4f7c254fbeab8fe9ee470fe5e5f7c"
uuid = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
version = "0.2.0"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "53fae3f45b6782dad91e932d941b0bf862110641"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.1"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Pkg", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "4a5e47a9cbae41414c8c1272686da3c374470d2d"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.8.1"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[GPUArrays]]
deps = ["FFTW", "LinearAlgebra", "Random", "Serialization", "StaticArrays", "Test"]
git-tree-sha1 = "00f6029786091ebc1f6283bd365fd850343cdeb7"
repo-rev = "sd/07"
repo-url = "https://github.com/JuliaGPU/GPUArrays.jl.git"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "0.2.4+"

[[GZip]]
deps = ["Compat"]
git-tree-sha1 = "37bd892cb1717e6fdbb82b8d2c7e3cb8ad89adb6"
uuid = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
version = "0.4.0"

[[GradDescent]]
git-tree-sha1 = "2fbb94817ad7b0f054d69cac2c49e474c089ba2d"
uuid = "e1397348-e965-55d8-8fb3-3dd9faf6e4f1"
version = "0.1.0"

[[Graphics]]
deps = ["Colors", "Compat", "NaNMath"]
git-tree-sha1 = "4671f2427ea4494a5d14fd485c4aa61ec1fb7cd2"
uuid = "a2bd30eb-e257-5431-a919-1863eab51364"
version = "0.3.0"

[[HDF5]]
deps = ["BinDeps", "Blosc", "Compat", "Homebrew", "Libdl", "WinRPM"]
git-tree-sha1 = "75c7918ef088ad01031229fb1d9efbf1cf96e9e7"
uuid = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
version = "0.9.3"

[[HTTP]]
deps = ["Base64", "Dates", "Distributed", "IniFile", "MbedTLS", "Sockets", "Test"]
git-tree-sha1 = "f1dd8a2e46970b318e2637aed47a21af033e3998"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.6.12"

[[HTTPClient]]
deps = ["Compat", "LibCURL"]
git-tree-sha1 = "161d5776ae8e585ac0b8c20fb81f17ab755b3671"
uuid = "0862f596-cf2d-50af-8ef4-f2be67dfa83f"
version = "0.2.1"

[[Homebrew]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "Unicode"]
git-tree-sha1 = "b8503955180201f902cc23dc0c299584c859f545"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.6.4"

[[ImageCore]]
deps = ["ColorTypes", "Colors", "FFTW", "FixedPointNumbers", "Graphics", "MappedArrays", "OffsetArrays", "PaddedViews", "Random", "Statistics", "Test"]
git-tree-sha1 = "b2745a0a4876ffc02ab64a343c8f357ec212a260"
uuid = "a09fc81d-aa75-5fe9-8630-4744c3626534"
version = "0.7.0"

[[IniFile]]
deps = ["Compat"]
git-tree-sha1 = "b86089c325a4287f7fc0a8240cbe2d591b1455c5"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.4.0"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LLVM]]
deps = ["InteractiveUtils", "Pkg", "Printf", "Test", "Unicode"]
git-tree-sha1 = "7e6b4251d1e607ebe6fee4432bac1f19debb215e"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "0.9.12"

[[LearnBase]]
deps = ["Compat", "StatsBase"]
git-tree-sha1 = "3c2162fbf99b257907730c5e389df385896654a9"
uuid = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
version = "0.1.6"

[[LibCURL]]
deps = ["BinDeps", "Compat", "Libdl", "WinRPM"]
git-tree-sha1 = "9b431bc66757ad5124f4d206c319996a2dfa2662"
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.2.2"

[[LibExpat]]
deps = ["Compat"]
git-tree-sha1 = "8ba2ca1635ec1755bcf1432c9a2aa6c91a3fb4fd"
uuid = "522f3ed2-3f36-55e3-b6df-e94fee9b0c07"
version = "0.4.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libz]]
deps = ["BufferedStreams", "Compat"]
git-tree-sha1 = "f26ee67f03d71be4633b21634755bc58e2457091"
uuid = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
version = "0.4.0"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MAT]]
deps = ["BufferedStreams", "Compat", "HDF5", "Libz"]
git-tree-sha1 = "2867125226f7815ccebca4cd67c719af2f07fb13"
uuid = "23992714-dd62-5051-b70f-ba57cb901cac"
version = "0.4.0"

[[MLDataPattern]]
deps = ["Compat", "LearnBase", "MLLabelUtils", "ShowItLikeYouBuildIt", "StatsBase"]
git-tree-sha1 = "78459bd1b8db97ad1773f5dfd0df7a0aa01e68df"
uuid = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
version = "0.4.0"

[[MLDataUtils]]
deps = ["DataFrames", "LearnBase", "MLDataPattern", "MLLabelUtils", "StatsBase"]
git-tree-sha1 = "f854fc565364bf969c193ad3027659e6da00b6e1"
uuid = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
version = "0.3.0"

[[MLDatasets]]
deps = ["BinDeps", "ColorTypes", "DataDeps", "FixedPointNumbers", "GZip", "ImageCore", "Libdl", "MAT"]
git-tree-sha1 = "e3b9dee2f4a3c49311084f162f4b288e9d105845"
uuid = "eb30cadb-4394-5ae3-aed4-317e484a6458"
version = "0.1.0"

[[MLLabelUtils]]
deps = ["LearnBase", "MappedArrays", "StatsBase"]
git-tree-sha1 = "b4ab1b332019f075a492651f7da534c53d9e3571"
uuid = "66a33bbf-0c2b-5fc8-a008-9da813334f0a"
version = "0.3.0"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "18c17737f3d375b86b495144ba7ab359ab3dca57"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.2"

[[MappedArrays]]
deps = ["Test"]
git-tree-sha1 = "94e68aa474f456f3f9a180171201c1ba61cf28d1"
uuid = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
version = "0.2.0"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["BinaryProvider", "Compat", "Sockets"]
git-tree-sha1 = "9c6b927293e9133277d8c99f06ab3d5470b34572"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "0.5.12"

[[MicroLogging]]
deps = ["Compat", "FastClosures"]
git-tree-sha1 = "53ef724928b9c23c30694ce9e490c478ce8724cf"
uuid = "cecf6091-0e4e-54ba-8cba-f0e96a51f282"
version = "0.2.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NNlib]]
deps = ["Libdl", "LinearAlgebra", "MacroTools", "Requires", "Test"]
git-tree-sha1 = "83dd97789dcd7718ae4f62ac7104e575894b7368"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
version = "0.4.0"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "7c4ca0f266081385e2ecf57fb210034f970cce5d"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.0"

[[PaddedViews]]
deps = ["OffsetArrays", "Test"]
git-tree-sha1 = "a6ecf172a704baa599ee1cc2c2953d129ce6aa31"
uuid = "5432bcbf-9aad-5242-b902-cca2824c8663"
version = "0.4.1"

[[Parameters]]
deps = ["Compat", "DataStructures", "REPL"]
git-tree-sha1 = "0ae7b8297f8a7ffb53672a64cb9e17b388357b57"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.9.1"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[ShowItLikeYouBuildIt]]
git-tree-sha1 = "e562bce4b0df3ed65562ce2ec7f56cb399368daf"
uuid = "9966252f-7483-59e3-9a4c-8607a6b2a5fe"
version = "0.2.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "1cf00baba50536d254f02082c90b98d6e4e1f968"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.6.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d998a83bc2cd507e12b08203e7523f2e60ac9ee6"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.2"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
repo-rev = "master"
repo-url = "https://github.com/JuliaStats/StatsBase.jl.git"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "d10e1e4b8fb8c6c50a1458c8e0de8f7abd0fc144"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.3"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "e8524bb636735227fd9d750dfa81f98db8bc5b0c"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.1"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"

[[WinRPM]]
deps = ["BinDeps", "Compat", "HTTPClient", "LibExpat", "Libdl", "Libz", "SHA", "URIParser"]
git-tree-sha1 = "c49429cfb38ece9ccb7604f9ca4c62ac1b772f4b"
uuid = "c17dfb99-b4f7-5aad-8812-456da1ad7187"
version = "0.3.3"

[[XGrad]]
deps = ["Espresso", "LinearAlgebra"]
git-tree-sha1 = "8fa109deb827b0decba041cee5deaed26a0b54c2"
repo-rev = "master"
repo-url = "https://github.com/dfdx/XGrad.jl.git"
uuid = "c48004fe-d13f-5df9-98d5-0c1ab8e45fa0"
version = "0.2.0"

[[Yota]]
deps = ["Espresso", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "6bdde2566dc535daeb4fa0b6c1216e5d3b4b4107"
repo-rev = "master"
repo-url = "/home/slipslop/work/Yota"
uuid = "f7b0de00-8e67-11e8-1ba4-09bec8501be6"
version = "0.1.0"
